create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  device_id text not null,
  water_detected boolean not null default false,
  measured_distance_cm double precision not null default 0,
  water_level_cm double precision not null default 0,
  last_water_level_cm double precision not null default 0,
  water_rising boolean not null default false,
  system_status text not null,
  power_mode text not null default 'USB_OR_BATTERY',
  timestamp timestamptz not null default now()
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  device_id text not null,
  alert_type text not null,
  message text not null,
  water_level_cm double precision not null default 0,
  timestamp timestamptz not null default now()
);

create index if not exists telemetry_timestamp_idx on telemetry (timestamp desc);
create index if not exists telemetry_device_timestamp_idx on telemetry (device_id, timestamp desc);
create index if not exists alerts_timestamp_idx on alerts (timestamp desc);
create index if not exists alerts_device_timestamp_idx on alerts (device_id, timestamp desc);

alter table telemetry enable row level security;
alter table alerts enable row level security;
